import { cn } from '../../lib/cn';
import { useSurface } from '../ui/surface';

/* ---------------------------------------------------------------------------
   LOGO — Trenvo's own mark.

   Not a client logo. §20.1 permits client logos only "with permission, and
   never before there are clients", and §26.2 keeps `Marquee` unbuilt for
   exactly that reason. This is the company's own identity and is unaffected.

   TWO VARIANTS, AND WHY BOTH ARE NEEDED.
   The artwork's navy measures 1.05:1 on --ink and 1.08:1 on --ink-soft — it is
   invisible on every dark surface, which includes the header overlay, the hero,
   the footer and all of the dark theme. The reversed asset preserves the exact
   silhouette filled with --paper. The surface context picks between them, the
   same mechanism that keeps §23.2's blue rule intact.

   FORMATS. §31.2: "AVIF with WebP fallback; srcset and sizes on everything;
   explicit dimensions on everything." <picture> gives the format ladder;
   width/height give the intrinsic box so nothing shifts (§29.2 "No layout
   shift"). Assets are generated by brand/build-assets.mjs.

   ⚠ These are raster. §31.2 asks for "SVG for all diagrams and icons", and a
   logo is vector artwork — a mark rendered at 28px from a raster is softer than
   it should be, and cannot be recoloured by CSS. Vector source is the right
   fix; see implementation.md §5.10.
--------------------------------------------------------------------------- */

/** Intrinsic ratios of the trimmed artwork, measured not assumed. */
const MARK_RATIO = 192 / 172;
const WORD_RATIO = 640 / 73;

export interface LogoProps {
  /** `mark` is the monogram alone; `lockup` adds the wordmark beside it. */
  variant?: 'mark' | 'lockup';
  /** Rendered height in px. Width follows the intrinsic ratio. */
  height?: number;
  /** Overrides the surface context, for use outside a Section. */
  reversed?: boolean;
  className?: string;
}

export function Logo({
  variant = 'lockup',
  height = 28,
  reversed,
  className,
}: LogoProps) {
  const surface = useSurface();
  const light = reversed ?? surface === 'dark';
  const suffix = light ? '-reversed' : '';

  const markW = Math.round(height * MARK_RATIO);
  const wordH = Math.round(height * 0.62); // the wordmark reads smaller than the mark
  const wordW = Math.round(wordH * WORD_RATIO);

  return (
    <span className={cn('inline-flex items-center gap-3', className)}>
      <picture>
        <source
          type="image/avif"
          srcSet={`/brand/logomark${suffix}-64.avif 64w, /brand/logomark${suffix}-96.avif 96w, /brand/logomark${suffix}-192.avif 192w`}
          sizes={`${markW}px`}
        />
        <source
          type="image/webp"
          srcSet={`/brand/logomark${suffix}-64.webp 64w, /brand/logomark${suffix}-96.webp 96w, /brand/logomark${suffix}-192.webp 192w`}
          sizes={`${markW}px`}
        />
        <img
          src={`/brand/logomark${suffix}-96.png`}
          width={markW}
          height={height}
          // §30.6 — the <a> that wraps this carries the accessible name, so the
          // image itself is decorative and must not repeat it.
          alt=""
          decoding="async"
          style={{ width: `${markW}px`, height: `${height}px` }}
        />
      </picture>

      {variant === 'lockup' && (
        <picture>
          <source
            type="image/avif"
            srcSet={`/brand/wordmark${suffix}-320.avif 320w, /brand/wordmark${suffix}-640.avif 640w`}
            sizes={`${wordW}px`}
          />
          <source
            type="image/webp"
            srcSet={`/brand/wordmark${suffix}-320.webp 320w, /brand/wordmark${suffix}-640.webp 640w`}
            sizes={`${wordW}px`}
          />
          <img
            src={`/brand/wordmark${suffix}-320.png`}
            width={wordW}
            height={wordH}
            alt=""
            decoding="async"
            // Below 380px the lockup crowds the header controls; the mark alone
            // still identifies the site.
            className="hidden min-[380px]:block"
            style={{ width: `${wordW}px`, height: `${wordH}px` }}
          />
        </picture>
      )}
    </span>
  );
}
